name = "speechtopics"
pages_build_output_dir = "./dist"

[ai]
binding = "AI"

[[d1_databases]]
binding = "DB"
database_name = "speechtopics"
database_id = "2ecc3066-ce72-494d-b828-6b668cf796ec"

[[queues.producers]]
binding = "EMAIL_QUEUE"
queue = "speechtopics-email"

